.TH GICN 1 20190213
.SH Name
.br
.PP
gicn \- Creating for study.
.br
.SH How to use
.B gicn
[OPTION]...[ARGUMENT]...
.br

.SS Initialize
.br
.B gicn
[ -i, --init ] [ vim | emacs | nano ]
.RS 4
Initialize setup.
.RE
.SS Help
.br
.B gicn
[ -h, --help ]
.RS 4
Display help.
.RE
.SS Version
.br
.B gicn
[ -v, --version ]
.RS 4
Display version.
.RE

.SH License
.PP
(C) 2019 mkncLab.com <https://www.mknclab.com/> / MIT LICENSE
.br
